### ISSUE TITLE
Openwrt backend validation problem for property ip_rules/src

### ISSUE THREAD

**Issue by hscadore** [openwisp/netjsonconfig#96]
Trying to generate a firewall rule for Openwrt causes an error because the library requires the zone definition "option src" (and option dest) to be an IP where they are actually zones according to openwrt documentation (https://wiki.openwrt.org/doc/uci/firewall).

I'm using netjsonconfig version 0.5.5.

**Comment by nemesisdesign** [comment]
Link to original discussion: https://groups.google.com/d/msg/openwisp/bHqaeCBBYhI/bywnzXfSCwAJ

**Comment by nemesisdesign** [comment]
After investigating this for a while, I found out there's a misunderstanding:

you are trying to use the policy routing feature (`ip rule`) instead of the firewall feature (which is basically a wrapper to iptables), **but the firewall feature is not supported in netjsonconfig yet** (you can use the [advanced mode and use the custom syntax to achieve what you need](http://netjsonconfig.openwisp.org/en/stable/backends/openwrt.html#all-the-other-settings)).

If you take a look at the documentation for ip rules in `/etc/config/network` you will see that `src` and `dest` are expected to be "*subnet to match (CIDR notation)*".

That said, it's still not good that the system fails with an exception, so I will address that issue for now.
